In [1]:
# quiz

def calc(a,b,c):
    if (a.isnumeric()==True) and (c.isnumeric()==True):
        a = int(a)
        c = int(c)
        if b == 'x':
            print('hasil dari', a,b,c, 'adalah', a*c)
        elif b == '+':
            print('hasil dari', a,b,c, 'adalah', a+c)
        elif b == ':':
            print('hasil dari', a,b,c, 'adalah', a/c)
        elif b == '-':
            print('hasil dari', a,b,c, 'adalah', a-c)
        elif b == '^':
            print('hasil dari', a,b,c, 'adalah', a**c)
        else:
            print('operator', b, 'tidak ditemukan')
    else:
        print('salah')
        
a=(input('masukan angka1 ='))
b=(input('masukan operator ='))
c=(input('masukan angka2 ='))

calc(a,b,c)

masukan angka1 =3
masukan operator =x
masukan angka2 =3
hasil dari 3 x 3 adalah 9


In [2]:
a = '3'
c.isnumeric()

True

In [3]:
try:
    int('string')
except:
    print('bukan string')

bukan string


In [4]:
# installing numpy
!pip install numpy

In [5]:
# import numpy
import numpy as np

In [6]:
# array adalah struktur data central dari perpustkaan NumPy
a=np.array([1,2,3])

In [7]:
print(a)

[1 2 3]


In [8]:
a[1]

2

ONE DIMENSIONAL ARRAY

In [9]:
array1 = np.array([1,2,3,4,5])
print(np.append(array1,[6,7]))

[1 2 3 4 5 6 7]


In [10]:
array1[2:]

array([3, 4, 5])

In [11]:
# shape itu baris, kolom
array1.shape

(5,)

2 DIMENSIONAL ARRAY

In [12]:
list = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
aray2 = np.array(list)
aray2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
print(aray2.shape)

(4, 3)


CREATING ARRAY

In [14]:
# np zeros untuk membuat array dengan isi angka 0
print(np.zeros(3)) #1D

[0. 0. 0.]


In [15]:
print(np.zeros([3,2])) #2D

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [16]:
# np ones untuk membuat array dengan isi angka 1
print(np.ones([2,2]))

[[1. 1.]
 [1. 1.]]


In [17]:
# np ones 
print(np.ones(3))

[1. 1. 1.]


In [18]:
# np empty untuk membuat array dengan isi random dan bergantung status memori
np.empty(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
# np arange untuk membuat array dengan jarak antar elemen
np.arange((10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
print(np.arange(0,4,2)) #start,stop,step. list np mulai dari angka 0 hingga 4 dengan kenaikan 2x untuk setiap loncatan

[0 2]


In [22]:
aray3 = np.array(((1,2,3,4)))
aray3.shape

(4,)

In [23]:
aray4 = np.array([[1,2,3,4]])
aray4.shape
# kalo kurung siku 1 brti ada 1 baris, kurung siku 2 ada 2 baris

(1, 4)

In [24]:
aray5 = np.array([[[1,2,3]]])
aray5.shape

(1, 1, 3)

In [25]:
# quiz

n=int(input('how tall ? '))
t=0

if n%2==0:
   t=n-1
else:
   t=n

for i in range(0,t):
   if (t-2*i)>0: 
      print(' '*i+'*'*(t-2*i))
   else:
      k=t-i-1
      print(' '*k+'*'*(t-2*k))

how tall ? 8
*******
 *****
  ***
   *
  ***
 *****
*******


In [26]:
x = np.array([1,2,3,4,5])

#append untuk menambahkan elemen ke array 
print(np.append(x,[6,7]))
#delete untuk menghapus elemen di array
print(np.delete(x,2))
#sort untuk menentukan axis, jenis, dan urutan saat memanggl fungsi
print(np.sort(x))

[1 2 3 4 5 6 7]
[1 2 4 5]
[1 2 3 4 5]


SHAPE AND SIZE

In [27]:
x = np.array([1,2,3,4,3,2,1,5,6,7,8,9,10])
y = np.zeros((3,3))
#ndim untuk memberi tahu jumlah axes atau dimensi dari array
print(x.ndim)
print(y.ndim)

#size untuk memberti tahu jumlah total elemen array
print(x.size)
print(y.size)

#reshape untuk memberikan bentuk baru ke array tanpa mengubah datanya
print(x[:-1].reshape(3,4))

1
2
13
9
[[1 2 3 4]
 [3 2 1 5]
 [6 7 8 9]]


In [28]:
# np.newaxis untuk menambah axis
a = np.array([1,2,3,4])
a.shape

a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 4)
[[1 2 3 4]]


In [29]:
# convert 1D ke 2D 
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 4)
[[1 2 3 4]]


In [30]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(4, 1)
[[1]
 [2]
 [3]
 [4]]


INDEXING & SLICING

In [31]:
b = np.array([1,2,3])
print(b)
print(b[0])
print(b[1])
print(b[2])
print(b[1:])
print(b[-1:])
print(b[b>=2])

[1 2 3]
1
2
3
[2 3]
[3]
[2 3]


In [32]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[2 4]


In [33]:
c = a[(a>1) & (a<3)]
print(c)

[2]


In [34]:
array3 = np.array([[1,2,3,4]])
array4 = np.array([[5,6,7,8]])
np.vstack([array3,array4]) #menumpuk array secara vertikal
print(np.hstack([array3,array4]))

[[1 2 3 4 5 6 7 8]]


In [35]:
array5 = np.array([1,2,3,4])
array6 = np.array([5,6,7,8])
np.hstack([array5,array6]) #menumpuk array secara horizontal

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
#stack
array1 = np.array([3,4,5,6,7])
array2 = np.array([7,8,9,10,11])
print('Stack secara Vertikal')
print(np.vstack([array1,array2]))
print('Stack secara Horizontal')
print(np.hstack([array1,array2]))

Stack secara Vertikal
[[ 3  4  5  6  7]
 [ 7  8  9 10 11]]
Stack secara Horizontal
[ 3  4  5  6  7  7  8  9 10 11]


In [37]:
#hsplit
array3 = np.array([3,4,5,6,7,8])
arraysplit = np.hsplit(array3,2)
(arraysplit)

[array([3, 4, 5]), array([6, 7, 8])]

In [38]:
#vsplit
array4 = np.array([[11,21,31,41],[41,51,61,71]])
print(array4.shape)
print('Horizontal Split')
print(np.hsplit(array4,2))
print('Vertical Split')
print(np.vsplit(array4,2))

(2, 4)
Horizontal Split
[array([[11, 21],
       [41, 51]]), array([[31, 41],
       [61, 71]])]
Vertical Split
[array([[11, 21, 31, 41]]), array([[41, 51, 61, 71]])]


In [39]:
np.append(array3,[11,12,13,14])

array([ 3,  4,  5,  6,  7,  8, 11, 12, 13, 14])

In [40]:
b = a.view()
b

array([1, 2, 3, 4])

In [41]:
c = a.copy
c

<function ndarray.copy>

In [42]:
#np.newaxis
array7 = np.array([21,22,23])
array7[np.newaxis]
print(array7[:,np.newaxis].shape)

(3, 1)


In [43]:
#np.expand_dims
array8 = np.array([23,24,25,26,27,28,29])
array9 = np.expand_dims(array8,axis=1)
array10 = np.expand_dims(array8,axis=0)
print(array9)
print(array9.shape)
print(array10)
print(array10.shape)

[[23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]]
(7, 1)
[[23 24 25 26 27 28 29]]
(1, 7)


OPERASI MATEMATIKA PADA ARRAY

In [44]:
array = np.array([1,2,3])
array*2

array([2, 4, 6])

In [45]:
array1 = np.array([[10,11,12],[13,14,15]])
array1-4

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [46]:
array1/2

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5]])

In [47]:
# menjumlahkan kolom array1 dengan yang beraxis 1
array1.sum(axis=1)

array([33, 42])

In [48]:
# menjumlahkan baris array1 dengan yang beraxis 0
array1.sum(axis=0)

array([23, 25, 27])

In [49]:
np.dot(a,b)

30

FILTERING ARRAY

In [50]:
array2 = np.array([100,200,300,400,500])
print(array2[array2>100])
print(array2[array2==400])
print(array2[array2<=800])

[200 300 400 500]
[400]
[100 200 300 400 500]


In [51]:
array3 = np.array([[1,3,5],[5,7,9],[-1,-2,-3]])
array3.shape
print(array3[array3>5])

[7 9]


In [52]:
print('aku mau \n nasi \n 11')

aku mau 
 nasi 
 11


OPERASI ARITMETIK ANTAR 2 ARRAY

In [53]:
array_a = np.array([1,2,3])
array_b = np.array([3,4,5])
print(array_a+array_b)

[4 6 8]


In [54]:
array_c = np.array([[1,2,3],[4,5,6]])
array_d = np.array([[6,7,8],[9,10,11]])
print(array_c-array_d)

[[-5 -5 -5]
 [-5 -5 -5]]


In [55]:
array_a = np.array([1,2,3])
array_b = np.array([3,4,5])
array_c = np.array([[1,2,3],[4,5,6]])
array_d = np.array([[6,7,8],[9,10,11]])
print(array_a.sum())
print(array_c.sum())
print(array_c.sum(axis=0))

6
21
[5 7 9]


In [56]:
array_c = np.array([[1,2,3],[4,5,6]])
print(array_c)
print(array_c.sum(axis=0))
print(array_c.sum(axis=1))

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]


In [57]:
array_a = np.array([1,2,3])
array_b = np.array([3,4,5])
array_c = np.array([[5,2,3],[4,5,6]])
print(array_a.max())
print(array_c.max())
print(array_c)
print(array_c.max(axis=0))
print(array_c.min(axis=0))

3
6
[[5 2 3]
 [4 5 6]]
[5 5 6]
[4 2 3]


TRANSPOSING 

merubah baris jadi kolom, kolom menjadi baris

In [58]:
arrayx = np.array([[5,2,3],[4,5,6]])
print(arrayx)
print(arrayx.shape)

[[5 2 3]
 [4 5 6]]
(2, 3)


In [59]:
print(arrayx.T)
print(arrayx.T.shape)

[[5 4]
 [2 5]
 [3 6]]
(3, 2)


In [60]:
arrayd = np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11]])
print(arrayd)
print(arrayd.shape)

[[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]]
(3, 5)


In [61]:
print(arrayd.T)
print(arrayd.T.shape)

[[ 1  4  7]
 [ 2  5  8]
 [ 3  6  9]
 [ 4  7 10]
 [ 5  8 11]]
(5, 3)


In [62]:
array_random = np.random.random([3,5])*100
print(array_random)

[[31.89231944 78.86036753  4.02048135 47.7639335  37.48565362]
 [15.77355552 77.60859146 29.39749273 26.11965664 96.57416762]
 [99.16617273 90.72352247 50.52011749 25.06891385 30.142528  ]]


In [63]:
array_random = np.random.random([3,1,2])*100
print(array_random)
print(array_random.flatten())

[[[50.95692796 28.54892127]]

 [[62.26044597  4.58241408]]

 [[39.42112093 53.84322056]]]
[50.95692796 28.54892127 62.26044597  4.58241408 39.42112093 53.84322056]


NUMPY MATH FORMULAS

In [64]:
array_random = np.random.random([1,2])*10
print(array_random)
np.sum(array_random)

[[6.5250762  5.27233781]]


11.797414009972295

In [65]:
np.square(58)

3364

In [66]:
np.sqrt(9)

3.0

In [67]:
a = np.log(100)
print(a)

4.605170185988092


In [68]:
np.exp(a)

100.00000000000004

In [69]:
# quiz bilangan prima

# First, we will take the input:  
lower_value = int(input ("Please, Enter the Lowest Range Value: "))  
upper_value = int(input ("Please, Enter the Upper Range Value: "))  
  
print ("The Prime Numbers in the range are: ")  
for number in range (lower_value, upper_value + 1):  
    if number > 1:  
        for i in range (2, number):  
            if (number % i) == 0:  
                break  
        else:  
            print (number)  

Please, Enter the Lowest Range Value: 1
Please, Enter the Upper Range Value: 20
The Prime Numbers in the range are: 
2
3
5
7
11
13
17
19
